#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

NPM_PACKAGES="${HOME}/.npm-packages"
#PATH="${HOME}/bin:${HOME}/anaconda/bin:$NPM_PACKAGES/bin:$PATH"
export PATH=${HOME}/bin:$NPM_PACKAGES/bin:$PATH

# pip should only run if virtualenv activated
export PIP_REQUIRE_VIRTUALENV=true

export WORKON_HOME=~/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

