#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

NPM_PACKAGES="${HOME}/.npm-packages"
export PATH=${HOME}/bin:$NPM_PACKAGES/bin:$PATH
export PATH=/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH
#export PATH=/Library/Frameworks/Mono.framework/Versions/Current/bin:$PATH
#export PATH="${HOME}/bin:${HOME}/anaconda/bin:$PATH"
# pip should only run if virtualenv activated
export PIP_REQUIRE_VIRTUALENV=true

export WORKON_HOME=~/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

